#!/bin/bash

for CUR in svgs/*.svg; do
    BASENAME=$CUR
    BASENAME=${BASENAME##*/}
    BASENAME=${BASENAME%.*}

    echo -ne "\033[0KGenerating png of  $BASENAME.svg\\r"

    inkscape -w 24 -h 24 --without-gui -f svgs/"$BASENAME".svg -e "pngs/$BASENAME.png" > /dev/null

done
